### ISSUE TITLE
Update to latest Pikascript core

### ISSUE THREAD

**Issue by maxgerhardt** [mimilib/mimiscript-demo-stm32#3]
This example seems to use an older API versions. Specifically 

https://github.com/pikasTech/pikascript-demo-stm32/blob/33d822741a941db65aaffe53de65101afa5aebb3/stm32f103c8t6/01-demo-pikascript-stm32f103c8t6-led/pikascript/pikascript-api/MyRoot-api.c#L11-L16

Where `obj_newObj(self, "led", "LED");` is used. But in the new core version, it needs to have a 4th parameter

https://github.com/pikasTech/pikascript/blob/5d5d4974d56f1b6482d7d521d054768f8cd06279/src/BaseObj.h#L39-L42

And so this project's main code can't be used directly with the new core.

**Comment by pikasTech** [comment]
This repo will not update anymore.
Actually this repo is moved to pikascript/bsp

And the bsps can be downloaded independently from 

http://pikascript.com

**Comment by maxgerhardt** [comment]
Where to? https://github.com/pikasTech/pikascript/blob/master/bsp/stm32f103c8/Booter/main.c does not have a LED test like iti s done here. In the `examples/` folders there are python-only examples.

**Comment by pikasTech** [comment]
The usage of this repo is out of date.
The obj_run and define_method now is done autoly by preCompiler.

**Comment by pikasTech** [comment]
> Where to? https://github.com/pikasTech/pikascript/blob/master/bsp/stm32f103c8/Booter/main.c does not have a LED test like iti s done here. In the `examples/` folders there are python-only examples.

from http://pikascript.com you can download demos (now renamed bsp) with core and modules installed.
